export const categories = [
  { title: "Credit Cards", icon: "CreditCardIcon" },
  { title: "Home Loans", icon: "HomeIcon" },
  { title: "Health Insurance", icon: "HeartIcon" },
  { title: "Car Insurance", icon: "HomeIcon" },
  { title: "High-Interest Savings", icon: "BuildingLibraryIcon" },
  { title: "Electricity & Gas", icon: "BoltIcon" },
  { title: "Personal Loans", icon: "BanknotesIcon" },
  { title: "Mobile Plans", icon: "DevicePhoneMobileIcon" },
  { title: "Broadban & NBN", icon: "ServerStackIcon" },
  { title: "Super funds", icon: "StarIcon" },
  { title: "Share Trading", icon: "HomeIcon" },
  { title: "Life Insurance", icon: "PaperAirplaneIcon" },
  { title: "Home Insurance", icon: "HomeIcon" },
  { title: "Travel Insurance", icon: "PaperAirplaneIcon" },
  { title: "Travel Deals", icon: "CalendarDaysIcon" },
  { title: "Crypto", icon: "CurrencyDollarIcon" },
  { title: "Car Loans", icon: "HomeIcon" },
  { title: "Pet Insurance", icon: "HomeIcon" },
  { title: "Transaction Accounts", icon: "CurrencyDollarIcon" },
  { title: "Money Transfers", icon: "HomeIcon" },
  { title: "Shopping Deals", icon: "ShoppingBagIcon" },
  { title: "Streaming", icon: "HomeIcon" },
  { title: "Business Insurance", icon: "CurrencyDollarIcon" },
  { title: "Short Term Loans", icon: "ClockIcon" },
];
